Fix ordering of query result
The original query put `interventionTitle` before
`dynamicFrameworkContractId`; this change rearranges the select to match
the same order

Fixes test errors eg

    java.lang.NullPointerException: Parameter specified as non-null is null: method uk.gov.justice.digital.hmpps.hmppsinterventionsservice.jpa.entity.ServiceProviderSentReferralSummary.<init>, parameter dynamicFrameWorkContractId
        at uk.gov.justice.digital.hmpps.hmppsinterventionsservice.service.ReferralServiceTest$GetServiceProviderSummaries.user with multiple providers can see referrals where the providers are subcontractors(ReferralServiceTest.kt:665)