Refactor: make test state obvious during failures
Makes the output of the test immediately hint at what might be wrong.

If I simulate the regression:

Before this change:

```
  Test in-progress referral EoSR check(Example) 4: in-progress delivery, with first substantive appointment (FSA) FAILED

  org.opentest4j.AssertionFailedError:
  expected: false
   but was: true
      at app//uk.gov.justice.digital.hmpps.hmppsinterventionsservice.service.ReferralConcluderTest.in-progress referral EoSR check(ReferralConcluderTest.kt:147)
```

After this change:

```
  Test [4] state=in-progress delivery, with first substantive appointment (FSA), expectation=ExpectThat(requiresEoSR=false, endingWith=null, concludesWith=null) FAILED

  org.opentest4j.AssertionFailedError: [requires end-of-service report]
  expected: false
   but was: true
      at app//uk.gov.justice.digital.hmpps.hmppsinterventionsservice.service.ReferralConcluderTest.in-progress referral EoSR check(ReferralConcluderTest.kt:137)
```

I feel this makes the failure quicker to understand:

- `state` is visible
- `expectation=ExpectThat(...)` is visible
- `[requires end-of-service report]`, `expected: false` and `was: true`
  makes it easy to see what was wrong
- `ReferralConcluderTest.in-progress referral EoSR check(...)` explains
  which test