Dashboard conditions should use table names
`assignedToUserName` and `concludedAt` were declared by the inner query
but since there is only one `SELECT` now, we have to use names from its
`FROM` clauses

Fixes errors like

    org.springframework.dao.InvalidDataAccessResourceUsageException: could not extract ResultSet; SQL [n/a]; nested exception is org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at app//uk.gov.justice.digital.hmpps.hmppsinterventionsservice.jpa.repository.ReferralRepositoryTest$DashboardTypeSelection.completed dashboard type should only return referrals that have been concluded(ReferralRepositoryTest.kt:361)
  Caused by: org.hibernate.exception.SQLGrammarException: could not extract ResultSet
        at app//uk.gov.justice.digital.hmpps.hmppsinterventionsservice.jpa.repository.ReferralRepositoryTest$DashboardTypeSelection.completed dashboard type should only return referrals that have been concluded(ReferralRepositoryTest.kt:361)
  Caused by: org.postgresql.util.PSQLException: ERROR: column "concludedat" does not exist
      Hint: Perhaps you meant to reference the column "r.concluded_at".
      Position: 1923
        at app//uk.gov.justice.digital.hmpps.hmppsinterventionsservice.jpa.repository.ReferralRepositoryTest$DashboardTypeSelection.completed dashboard type should only return referrals that have been concluded(ReferralRepositoryTest.kt:361)